#!/usr/bin/env python

from __future__ import absolute_import
from __future__ import unicode_literals

import os
import sys
import yaml

main_path = __file__

while os.path.islink (main_path):
	main_path = os.readlink (main_path)

SCRIPT = os.path.basename (__file__)
HOME = os.path.abspath (os.path.dirname (main_path) + "/../../..")

import gridlinker

METADATA = gridlinker.metadata.load (HOME)
CONNECTION = os.environ [METADATA ["environment"] ["devops_connection_name"]]

context = gridlinker.GenericContext (HOME, CONNECTION, METADATA)

gridlinker.ansible.inventory.main (context, sys.argv [1:])

# ex: noet ts=4 filetype=python
