---

- name: "remove icinga system packages"
  with_items:

    - "icinga2"
    - "icinga2-bin"
    - "icinga2-common"
    - "icinga2-doc"
    - "icinga2-ido-mysql"
    - "icinga2-ido-pgsql"
    - "libicinga2"

  become: "yes"
  action:

    module: "apt"
    name: "{{ item }}"
    state: "absent"
    purge: "yes"

- name: "install icinga system package dependencies"
  with_items: "{{ icinga_core_install_system_packages }}"
  become: "yes"
  action:

    module: "apt"
    name: "{{ item }}"
    state: "present"
    purge: "yes"

- name: "create icinga group"
  become: "yes"
  action:

    module: "group"
    name: "icinga"
    system: "yes"

- name: "create icinga user"
  become: "yes"
  action:

    module: "user"
    name: "icinga"
    system: "yes"
    group: "icinga"

- name: "add ubuntu to icinga group"
  become: "yes"
  action:

    module: "user"
    name: "ubuntu"
    groups: "icinga"
    append: "yes"

- name: "install icinga"
  changed_when: "icinga_core_installed_version != icinga_core_install_version"
  become: "yes"
  args:

    executable: "/bin/bash"

  shell:

    set -euf -o pipefail;

    if test "{{ icinga_core_installed_version }}"
        == "{{ icinga_core_install_version }}"; then
      exit 0;
    fi;

    rm -rf "{{ icinga_core_install_temp }}";
    mkdir -p "{{ icinga_core_install_temp }}";
    cd "{{ icinga_core_install_temp }}";

    wget "{{ icinga_core_install_url }}";

    tar
      --extract
      --xz
      --file "{{ icinga_core_install_archive }}";

    mkdir -p "{{ icinga_core_install_prefix }}";

    rsync
      --archive
      --delete
      {{ icinga_core_install_directory }}/
      {{ icinga_core_install_prefix }}/
      --exclude /etc
      --exclude /var;

    rm -rf {{ icinga_core_install_temp }};

    mkdir -p
      "{{ icinga_core_install_prefix }}/etc"
      "{{ icinga_core_install_prefix }}/var/cache"
      "{{ icinga_core_install_prefix }}/var/lib"
      "{{ icinga_core_install_prefix }}/var/log"
      "{{ icinga_core_install_prefix }}/var/run";

    ln -sfn
      "/etc/icinga2"
      "{{ icinga_core_install_prefix }}/etc/icinga2";

    ln -sfn
      "/var/cache/icinga2"
      "{{ icinga_core_install_prefix }}/var/cache/icinga2";

    ln -sfn
      "/var/lib/icinga2"
      "{{ icinga_core_install_prefix }}/var/lib/icinga2";

    ln -sfn
      "/var/log/icinga2"
      "{{ icinga_core_install_prefix }}/var/log/icinga2";

    ln -sfn
      "/var/run/icinga2"
      "{{ icinga_core_install_prefix }}/var/run/icinga2";

- name: "set icinga_core.state to 'installed'"
  when: "icinga_core_state == ''"
  update_resource:

    icinga_core.state: "installed"

- name: "set icinga_core.installed_version"
  when: "icinga_core_installed_version != icinga_core_install_version"
  update_resource:

    icinga_core.installed_version: "{{ icinga_core_install_version }}"

- name: "set icinga_core.installed_prefix"
  when: "icinga_core_installed_prefix != icinga_core_install_prefix"
  update_resource:

    icinga_core.installed_prefix: "{{ icinga_core_install_prefix }}"

# ex: et ts=2 filetype=yaml
