---

- name: "write postgresql systemd config"
  register: "postgresql_control_systemd_config_result"
  become: "yes"
  action:

    module: "template"
    dest: "/etc/systemd/system/postgresql.service"
    src: "postgresql-control-systemd"

- name: "postgresql systemd daemon reload"
  when: "postgresql_control_systemd_config_result | changed"
  become: "yes"
  command: "systemctl daemon-reload"

- name: "set postgresql.needs_restart to 'yes'"
  when: "postgresql_control_systemd_config_result | changed"
  update_resource:

    postgresql.needs_restart: "yes"

- name: "postgresql control systemd stop"
  when: "postgresql_state != 'enabled'"
  become: "yes"
  action:

    module: "service"
    name: "postgresql"
    state: "stopped"
    enabled: "no"

- name: "postgresql control systemd start"
  when: "postgresql_state == 'enabled'"
  register: "postgresql_control_systemd_start_result"
  become: "yes"
  action:

    module: "service"
    name: "postgresql"
    state: "started"
    enabled: "yes"

- name: "set postgresql.needs_restart to 'no'"
  when: "postgresql_control_systemd_start_result | changed"
  update_resource:

    postgresql.needs_restart: "no"

- name: "postgresql control systemd restart"
  when: "postgresql_needs_restart == 'yes'"
  register: "postgresql_control_systemd_restart_result"
  become: "yes"
  action:

    module: "service"
    name: "postgresql"
    state: "restarted"

- name: "set postgresql.needs_restart to 'no'"
  when: "postgresql_control_systemd_restart_result | changed"
  update_resource:

    postgresql.needs_restart: "no"

- name: "postgresql control systemd reload"
  when: "
    not (
      postgresql_control_systemd_start_result | changed
    ) and not (
      postgresql_control_systemd_restart_result | changed
    )
  "
  changed_when: "False"
  register: "postgresql_control_systemd_reload_result"
  become: "yes"
  action:

    module: "service"
    name: "postgresql"
    state: "reloaded"

- name: "create postgresql user 'ubuntu'"
  become: "yes"
  become_user: "postgres"
  action:

    module: "postgresql_user"
    name: "ubuntu"

    role_attr_flags: "SUPERUSER"

    login_unix_socket: "/var/run/postgresql"

# ex: et ts=2 filetype=yaml
