---

- name: "mysql install from distro set dpkg config"
  with_items:

    - package: "mysql-server"
      question: "mysql-server/root_password"
      answer: "{{ mysql_root_password }}"
      type: "password"

    - package: "mysql-server"
      question: "mysql-server/root_password_again"
      answer: "{{ mysql_root_password }}"
      type: "password"

  become: "yes"
  action:

    module: "debconf"
    name: "{{ item.package }}"
    question: "{{ item.question }}"
    value: "{{ item.answer }}"
    vtype: "{{ item.type }}"

- name: "install mysql packages"
  with_items: "{{ mysql_distro_packages }}"
  become: "yes"
  action:

    module: "apt"
    name: "{{ item }}"

- name: "set mysql root password"
  register: "mysql_root_password_result"
  changed_when: "mysql_root_password_result.stdout != 'UNCHANGED'"
  args:

    executable: "/bin/bash"

  shell:

    set -euf -o pipefail;

    if ! mysql
      --user="root"
      --password=""
      --execute="select 1"
      >/dev/null;
    then
      echo "UNCHANGED";
      exit 0;
    fi;

    mysql "mysql"
      --user="root"
      --password=""
      --execute="

        DELETE FROM user
        WHERE user = 'root'
        AND host != '%';

        GRANT ALL PRIVILEGES
        ON *.*
        TO root@'%'
        IDENTIFIED BY '{{ mysql_root_password }}'
        WITH GRANT OPTION;

        FLUSH PRIVILEGES;

      ";

    echo "CHANGED";
    exit 0;

- name: "disable mysql sysv init"
  register: "mysql_sysv_result"
  changed_when: "mysql_sysv_result.stdout != 'UNCHANGED'"
  become: "yes"
  args:

    executable: "/bin/bash"

  shell:

    set -euf -o pipefail;

    test -e /etc/init.d/mysql || { echo "UNCHANGED"; exit 0; };
    service mysql stop;
    rm -f /etc/init.d/mysql /etc/init.d/rc?.d/[KS]??mysql;

- name: "set mysql.state to 'installed'"
  when: "mysql_state == ''"
  update_resource:

    mysql.state: "installed"

- name: "set mysql.installed_from to 'distro'"
  when: "mysql_installed_from != 'distro'"
  update_resource:

    mysql.installed_from: "distro"

# ex: et ts=2 filetype=yaml
