---

- name: "create ido database"
  delegate_to: "{{ icinga_core_database_delegate }}"
  register: "icinga_database_create_result"
  action:

    module: "postgresql_db"
    name: "{{ icinga_core_database_name }}"

    login_user: "ubuntu"
    login_unix_socket: "/var/run/postgresql"

- name: "set icinga_core_database_initialized to 'no'"
  when: "icinga_database_create_result | changed"
  update_resource:

    icinga_core.database_initialized: "no"

- name: "create ido user"
  delegate_to: "{{ icinga_core_database_delegate }}"
  action:

    module: "postgresql_user"
    name: "{{ icinga_core_database_username }}"

    password: "{{ icinga_core_database_password }}"
    db: "{{ icinga_core_database_name }}"

    login_user: "ubuntu"
    login_unix_socket: "/var/run/postgresql"

- name: "grant icinga database permissions"
  with_items:

    - "table"
    - "sequence"

  delegate_to: "{{ icinga_core_database_delegate }}"
  action:

    module: "postgresql_privs"
    role: "{{ icinga_core_database_username }}"
    state: "present"

    database: "{{ icinga_core_database_name }}"
    schema: "public"
    objs: "ALL_IN_SCHEMA"
    type: "{{ item }}"

    privs: "ALL"

    login_user: "ubuntu"
    login_unix_socket: "/var/run/postgresql"

- name: "initialize ido database"
  when: "icinga_core_database_initialized != 'yes'"
  delegate_to: "{{ icinga_core_database_delegate }}"
  args:

    executable: "/bin/bash"

  shell:

    set -euf -o pipefail;

    psql {{ icinga_core_database_name }}
      < "{{ [
        hostvars [icinga_core_database_delegate].icinga_core_installed_prefix,
        '/share/icinga2-ido-pgsql/schema/pgsql.sql',
      ] | join }}";

- name: "set icinga_core.database_initialized to 'yes'"
  update_resource:

    icinga_core.database_initialized: "yes"

# ex: et ts=2 filetype=yaml
