---

- name: "create icinga web database"
  delegate_to: "{{ icinga_web_core_database_delegate }}"
  register: "icinga_web_core_database_create_result"
  action:

    module: "postgresql_db"
    name: "{{ icinga_web_core_database_name }}"

    login_user: "ubuntu"
    login_unix_socket: "/var/run/postgresql"

- name: "set icinga_web_core.database_initialized to 'no'"
  when: "icinga_web_core_database_create_result | changed"
  update_resource:

    icinga_web_core.database_initialized: "no"

- name: "create icinga web ido database user"
  delegate_to: "{{ icinga_web_core_ido_database_delegate }}"
  action:

    module: "postgresql_user"
    name: "{{ icinga_web_core_ido_database_username }}"

    password: "{{ icinga_web_core_ido_database_password }}"
    db: "{{ icinga_web_core_ido_database_name }}"

    login_user: "ubuntu"
    login_unix_socket: "/var/run/postgresql"

- name: "grant icinga web ido database permissions"
  delegate_to: "{{ icinga_web_core_ido_database_delegate }}"
  action:

    module: "postgresql_privs"
    role: "{{ icinga_web_core_ido_database_username }}"
    state: "present"

    database: "{{ icinga_web_core_ido_database_name }}"
    schema: "public"
    objs: "ALL_IN_SCHEMA"
    type: "table"

    privs: "SELECT"

    login_user: "ubuntu"
    login_unix_socket: "/var/run/postgresql"

- name: "create icinga web main database user"
  delegate_to: "{{ icinga_web_core_database_delegate }}"
  action:

    module: "postgresql_user"
    name: "{{ icinga_web_core_database_username }}"

    password: "{{ icinga_web_core_database_password }}"
    db: "{{ icinga_web_core_database_name }}"

    login_user: "ubuntu"
    login_unix_socket: "/var/run/postgresql"

- name: "grant icinga web main database permissions"
  with_items:

    - "table"
    - "sequence"

  delegate_to: "{{ icinga_web_core_database_delegate }}"
  action:

    module: "postgresql_privs"
    role: "{{ icinga_web_core_database_username }}"
    state: "present"

    database: "{{ icinga_web_core_database_name }}"
    schema: "public"
    objs: "ALL_IN_SCHEMA"
    type: "{{ item }}"

    privs: "ALL"

    login_user: "ubuntu"
    login_unix_socket: "/var/run/postgresql"

- name: "initialize icinga web database"
  delegate_to: "{{ icinga_web_core_database_delegate }}"
  when: "icinga_web_core_database_initialized != 'yes'"
  args:

    executable: "/bin/bash"

  environment:

    PGHOST: "{{ icinga_web_core_database_hostname }}"
    PGPORT: "{{ icinga_web_core_database_port }}"
    PGUSER: "{{ icinga_web_core_database_username }}"
    PGPASSWORD: "{{ icinga_web_core_database_password }}"

  shell:

    set -euf -o pipefail;

    psql
      --dbname "{{ icinga_web_core_database_name }}"
      --file "{{ [
        hostvars [icinga_web_core_database_delegate]
          .icinga_web_core_installed_prefix,
        '/etc/schema/pgsql.schema.sql',
      ] | join }}"
      --set "ON_ERROR_STOP=on";

- name: "set icinga_web_core_database_initialized to 'yes'"
  when: "icinga_web_core_database_initialized != 'yes'"
  update_resource:

    icinga_web_core.database_initialized: "yes"

- name: "icinga web database setup postgresql write data script"
  register: "icinga_web_core_database_script_result"
  delegate_to: "{{ icinga_web_core_database_delegate }}"
  action:

    module: "template"
    dest: "/tmp/icinga-web-users.sql"
    src: "icinga-web-database-setup-postgresql-users"

    mode: "0600"

- name: "icinga web database setup postgresql run data script"
  changed_when: "icinga_web_core_database_script_result | changed"
  delegate_to: "{{ icinga_web_core_database_delegate }}"
  args:

    executable: "/bin/bash"

  environment:

    PGHOST: "{{ icinga_web_core_database_hostname }}"
    PGPORT: "{{ icinga_web_core_database_port }}"
    PGUSER: "{{ icinga_web_core_database_username }}"
    PGPASSWORD: "{{ icinga_web_core_database_password }}"

  shell:

    set -euf -o pipefail;

    psql
      --dbname "{{ icinga_web_core_database_name }}"
      --file "/tmp/icinga-web-users.sql"
      --set ON_ERROR_STOP=on;

# ex: et ts=2 filetype=yaml
