---

# ---------- state

icinga_core_state: ""
icinga_core_needs_restart: ""

icinga_core_installed_version: ""
icinga_core_installed_prefix: ""

# ---------- runtime defaults

icinga_core_common_name: "{{ identity_name }}"
icinga_core_alt_dns: [ "{{ icinga_core_common_name }}" ]
icinga_core_alt_ips: []

icinga_core_database_delegate: "{{ icinga_core_master }}"
icinga_core_database_type: ""
icinga_core_database_name: "icinga"
icinga_core_database_username: "icinga"
icinga_core_database_password: ""
icinga_core_database_initialized: "no"

icinga_core_ticket_salt: ""

icinga_core_ca_certificate: ""
icinga_core_certificate: ""
icinga_core_private_key: ""

# ---------- installation

icinga_core_install: ""
icinga_core_install_version: ""
icinga_core_install_prefix: "/opt/icinga-{{ icinga_core_install_version }}"

icinga_core_install_system_packages: "{{
  icinga_core_install_system_packages_by_release [ubuntu_release]
}}"

icinga_core_install_system_packages_by_release:

  trusty:

    - "libboost-program-options1.54.0"
    - "libboost-regex1.54.0"
    - "libboost-thread1.54.0"
    - "libyajl2"
    - "nagios-plugins-basic"

  xenial:

    - "libboost-program-options1.58.0"
    - "libboost-regex1.58.0"
    - "libboost-thread1.58.0"
    - "libyajl2"
    - "nagios-plugins-basic"

icinga_core_install_temp: "/tmp/icinga-install"
icinga_core_install_dist: "https://dist.wellbehavedsoftware.com"
icinga_core_install_mirror: "{{ icinga_core_install_dist }}/icinga"
icinga_core_install_directory: "icinga-{{ icinga_core_install_version }}"
icinga_core_install_archive: "{{ icinga_core_install_directory }}.tar.xz"
icinga_core_install_url: "{{ icinga_core_install_mirror }}/{{ icinga_core_install_archive }}"

# ---------- master configuration

icinga_core_master_endpoints: "icinga-masters"
icinga_core_master_agents: "icinga-agents"
icinga_core_master_hosts: "icinga-hosts"

icinga_core_master_users: "icinga-users"
icinga_core_master_groups: "icinga-groups"

icinga_core_master_services: []

icinga_core_master_directories:

  - directory: "/etc/icinga2"
    user: "icinga"
    group: "icinga"
    mode: "0750"

  - directory: "/etc/icinga2/pki"
    user: "icinga"
    group: "icinga"
    mode: "0750"

  - directory: "/etc/icinga2/scripts"
    user: "icinga"
    group: "icinga"
    mode: "0750"

  - directory: "/etc/icinga2/zones.d"
    user: "icinga"
    group: "icinga"
    mode: "0750"

  - directory: "/var/cache/icinga2"
    user: "icinga"
    group: "icinga"
    mode: "0750"

  - directory: "/var/lib/icinga2"
    user: "icinga"
    group: "icinga"
    mode: "0750"

  - directory: "/var/lib/icinga2/api"
    user: "icinga"
    group: "icinga"
    mode: "0750"

  - directory: "/var/lib/icinga2/api/log"
    user: "icinga"
    group: "icinga"
    mode: "0750"

  - directory: "/var/lib/icinga2/api/repository"
    user: "icinga"
    group: "icinga"
    mode: "0750"

  - directory: "/var/lib/icinga2/api/zones"
    user: "icinga"
    group: "icinga"
    mode: "0750"

  - directory: "/var/log/icinga2"
    user: "icinga"
    group: "icinga"
    mode: "0750"

icinga_core_master_config_templates:

  - template: "icinga-master-commands"
    target: "commands.conf"
    mode: "0644"

  - template: "icinga-master-constants"
    target: "constants.conf"
    mode: "0644"

  - template: "icinga-master-hosts"
    target: "hosts.conf"
    mode: "0644"

  - template: "icinga-master-icinga"
    target: "icinga2.conf"
    mode: "0644"

  - template: "icinga-master-notifications"
    target: "notifications.conf"
    mode: "0644"

  - template: "icinga-master-script-mail"
    target: "scripts/mail"
    mode: "0755"

  - template: "icinga-master-secrets"
    target: "secrets.conf"
    mode: "0640"

  - template: "icinga-master-services"
    target: "services.conf"
    mode: "0644"

  - template: "icinga-master-time-periods"
    target: "time-periods.conf"
    mode: "0644"

  - template: "icinga-master-users"
    target: "users.conf"
    mode: "0644"

  - template: "icinga-master-zones"
    target: "zones.conf"
    mode: "0644"

icinga_core_master_security_files:

  - source: "{{ icinga_core_ca_certificate }}"
    target: "pki/ca.cert"
    mode: "0644"

  - source: "{{ icinga_core_certificate }}"
    target: "pki/{{ identity.name }}.cert"
    mode: "0644"

  - source: "{{ icinga_core_private_key }}"
    target: "pki/{{ identity.name }}.key"
    mode: "0640"

icinga_core_master_links:

  - link: "{{ icinga_installed_prefix }}/etc"
    target: "../../etc"

  - link: "{{ icinga_installed_prefix }}/var"
    target: "../../var"

# ---------- agent configuration

icinga_core_agent_masters: "icinga-masters"

icinga_core_agent_directories:

  - directory: "/etc/icinga2"
    user: "icinga"
    group: "icinga"
    mode: "0750"

  - directory: "/etc/icinga2/pki"
    user: "icinga"
    group: "icinga"
    mode: "0750"

  - directory: "/etc/icinga2/scripts"
    user: "icinga"
    group: "icinga"
    mode: "0750"

  - directory: "/etc/icinga2/zones.d"
    user: "icinga"
    group: "icinga"
    mode: "0750"

  - directory: "/var/cache/icinga2"
    user: "icinga"
    group: "icinga"
    mode: "0750"

  - directory: "/var/lib/icinga2"
    user: "icinga"
    group: "icinga"
    mode: "0750"

  - directory: "/var/lib/icinga2/api"
    user: "icinga"
    group: "icinga"
    mode: "0750"

  - directory: "/var/lib/icinga2/api/log"
    user: "icinga"
    group: "icinga"
    mode: "0750"

  - directory: "/var/lib/icinga2/api/repository"
    user: "icinga"
    group: "icinga"
    mode: "0750"

  - directory: "/var/lib/icinga2/api/zones"
    user: "icinga"
    group: "icinga"
    mode: "0750"

  - directory: "/var/log/icinga2"
    user: "icinga"
    group: "icinga"
    mode: "0750"

icinga_core_agent_config_templates:

  - template: "icinga-agent-constants"
    target: "constants.conf"
    mode: "0644"

  - template: "icinga-agent-icinga"
    target: "icinga2.conf"
    mode: "0644"

  - template: "icinga-agent-secrets"
    target: "secrets.conf"
    mode: "0640"

  - template: "icinga-agent-zones"
    target: "zones.conf"
    mode: "0644"

icinga_core_agent_security_files:

  - source: "{{ icinga_core_ca_certificate }}"
    target: "pki/ca.cert"
    mode: "0644"

  - source: "{{ icinga_core_certificate }}"
    target: "pki/{{ identity_name }}.cert"
    mode: "0644"

  - source: "{{ icinga_core_private_key }}"
    target: "pki/{{ identity_name }}.key"
    mode: "0640"

icinga_core_agent_links:

  - link: "{{ icinga_core_installed_prefix }}/etc"
    target: "../../etc"

  - link: "{{ icinga_core_installed_prefix }}/var"
    target: "../../var"

# ---------- agent configuration

icinga_core_host_vars: {}

# ex: et ts=2 filetype=yaml
