---

- name: "create icingaweb2 group"
  become: "yes"
  action:

    module: "group"
    name: "icingaweb2"
    system: "yes"

- name: "add www-data to icingaweb2 group"
  notify: "restart php"
  become: "yes"
  action:

    module: "user"
    name: "www-data"
    groups: "icingaweb2"
    append: "yes"

- name: "install icinga-web"
  when: "icinga_web_core_installed_version != icinga_web_core_install_version"
  become: "yes"
  args:

    executable: "/bin/bash"

  shell:

    set -euf -o pipefail;

    rm -rf {{ icinga_web_core_install_temp }};
    mkdir -p {{ icinga_web_core_install_temp }};
    cd {{ icinga_web_core_install_temp }};

    wget {{ icinga_web_core_install_url }};
    tar xzf {{ icinga_web_core_install_archive }};

    mkdir -p {{ icinga_web_core_install_prefix }};

    rsync --archive --delete
      {{ icinga_web_core_install_directory }}/
      {{ icinga_web_core_install_prefix }}/;

    rm -rf {{ icinga_web_core_install_temp }};

- name: "link icinga-web"
  become: "yes"
  action:

    module: "file"
    path: "/opt/icinga-web"
    state: "link"

    src: "icinga-web-{{ icinga_web_core_install_version }}"
    force: "yes"

- name: "set icinga_web_core.state to 'installed'"
  when: "icinga_web_core_state == ''"
  update_resource:

    icinga_web_core.state: "installed"

- name: "set icinga_web_core.installed_version"
  when: "icinga_web_core_installed_version != icinga_web_core_install_version"
  update_resource:

    icinga_web_core.installed_version: "{{ icinga_web_core_install_version }}"

- name: "set icinga_web_core.installed_prefix"
  when: "icinga_web_core_installed_prefix != icinga_web_core_install_prefix"
  update_resource:

    icinga_web_core.installed_prefix: "{{ icinga_web_core_install_prefix }}"

# ex: et ts=2 filetype=yaml
