---

- name: "write etcd upstart config"
  when: "system_init == 'upstart'"
  become: "yes"
  action:

    module: "template"
    dest: "/etc/init/etcd.conf"
    src: "etcd-upstart"

- name: "write etcd systemd config"
  when: "system_init == 'systemd'"
  become: "yes"
  action:

    module: "template"
    dest: "/etc/systemd/system/etcd.service"
    src: "etcd-systemd"

- name: "start etcd"
  when: "etcd_state == 'enabled'"
  become: "yes"
  action:

    module: "service"
    name: "etcd"
    state: "started"

- name: "reload etcd"
  changed_when: "False"
  become: "yes"
  action:

    module: "service"
    name: "etcd"
    state: "reloaded"

- name: "stop etcd"
  when: "etcd_state == 'disabled'"
  become: "yes"
  action:

    module: "service"
    name: "etcd"
    state: "stopped"

# ex: et ts=2 filetype=yaml
